
services:
  app:
    environment:
      APP_SECRET_FILE: ""
      DATABASE_URL_FILE: ""
    volumes:
      - .:/var/www/html # Code source en developpement

  database:
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD_FILE: ""
      MYSQL_DATABASE_FILE: ""
      MYSQL_PASSWORD_FILE: ""

  webserver:
    volumes:
      - .:/var/www/html # Code source en developpement
      - ./nginx:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
